//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomORM {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ORMResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ORMResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomORM.ORMResource", typeof(ORMResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IF EXISTS(SELECT 1 FROM sys.procedures 
        ///                                        WHERE Name = &apos;sp_getFkData&apos;)
        ///                                        BEGIN SELECT 1; END
        ///                                        ELSE 
        ///                                        BEGIN SELECT 0; END.
        /// </summary>
        internal static string sp_getFkData_Check_Existense {
            get {
                return ResourceManager.GetString("sp_getFkData_Check_Existense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE PROC sp_getFkData( @tableName nvarchar(20))
        ///AS
        ///BEGIN
        ///SELECT 
        ///    tab1.name AS [Child_Table],
        ///    col1.name AS [FK_ColumnName],
        ///    tab2.name AS [Parent_Table],
        ///    col2.name AS [PK_ColumnName]
        ///FROM sys.foreign_key_columns fkc
        ///INNER JOIN sys.objects obj
        ///    ON obj.object_id = fkc.constraint_object_id
        ///INNER JOIN sys.tables tab1
        ///    ON tab1.object_id = fkc.parent_object_id
        ///INNER JOIN sys.schemas sch
        ///    ON tab1.schema_id = sch.schema_id
        ///INNER JOIN sys.columns col1
        ///    ON col1.column_id = [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sp_getFkData_Creation_Script {
            get {
                return ResourceManager.GetString("sp_getFkData_Creation_Script", resourceCulture);
            }
        }
    }
}
